export const LANDING = '/';
// export const SIGN_UP = "/signup"
export const LOGIN = '/login';
export const HOME = '/home';
export const USERS = '/users';
export const GROUPS = '/groups';
export const ITINERARY = '/itinerary';
export const NOTIFICATIONS = '/notifications';
export const ALARM = '/alarm';
export const LOST = '/lost';
export const CONTACT = '/contact';
export const CONTENT = '/content';
export const SETTINGS = '/settings';
